/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.onlineRS;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author MCOPHEMMZ
 */
public class Main extends javax.swing.JFrame {
    

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    public void close(){
    WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmd_reservation = new javax.swing.JButton();
        cmd_cancellation = new javax.swing.JButton();
        cmd_pnr = new javax.swing.JButton();
        cmd_exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmd_reservation.setText("Reservation Form");
        cmd_reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_reservationActionPerformed(evt);
            }
        });
        getContentPane().add(cmd_reservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        cmd_cancellation.setText("Cancellation Form");
        getContentPane().add(cmd_cancellation, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        cmd_pnr.setText("PNR Enquiry");
        getContentPane().add(cmd_pnr, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        cmd_exit.setText("Exit");
        getContentPane().add(cmd_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/onlineRS/indian-rail.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 881, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_reservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_reservationActionPerformed
                    

        Reservation r= new Reservation();
        r.setVisible(true);
        close();
        
    }//GEN-LAST:event_cmd_reservationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_cancellation;
    private javax.swing.JButton cmd_exit;
    private javax.swing.JButton cmd_pnr;
    private javax.swing.JButton cmd_reservation;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
